spring:
  rsocket:
    server:
      port: 7000
      transport: tcp
  data:
    mongodb:
      host: localhost
      port: 27017
      database: messenger_db

#  autoconfigure:
#    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration

logging:
  level:
    org:
      springframework:
        security: DEBUG





