spring:
  rsocket:
    server:
      port: 7000
      transport: tcp
  data:
    mongodb:
      host: localhost
      port: 27017
      database: messenger_db

logging:
  level:
    org:
      springframework:
        security: DEBUG





